version: "3"

services:
  api:
    image: "node-api"
    build: .
    container_name: "API"
    command: npm start
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./api:/usr/api
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: "MongoDB"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db