version: "3"

services:
  api:
    image: node:latest
    user: "node"
    working_dir: /home/node/app
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "3001"
    command: "npm start"
